# ----------------------------
# ALIAS
# ----------------------------
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias weather='ansiweather -l "Los Gatos,US" -u imperial -s true -d true'
alias f='thefuck'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias qfind="find . -name "
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias c='clear'
alias hclear='history -c; clear'
#alias ll='ls -l -a -G -F -h'
#alias ls='ls -lahF'
alias ls='exa'
alias ll='exa -lahF'
alias vi='vim'
alias ip='/sbin/ifconfig'
alias tidy_xml='tidy -utf8 -xml -w 255 -i -c -q -asxml'
alias df='df -h'
alias du='du -ch'
alias diskspace="du -S | sort -n -r |more"
alias chomp="tr -d'\n'"
alias grep='grep --color=auto'
alias ping='ping -c 5'
alias reboot='sudo /sbin/reboot'
alias shutdown='sudo /sbin/shutdown -t now'
alias prettyjson='python -m json.tool'
alias db_mysql='mysql -h localhost -u root'
alias tl='tldr'
alias ga='git add -A'
alias gc='git commit -m '
alias gp='git push'
alias gs='git status'
alias gd='git diff'
alias open='xdg-open'
